name: packt
channels:
  - conda-forge
  - anaconda
dependencies:
  - anaconda:python=3.7.3
  - anaconda:black
  - anaconda:scikit-learn==0.21.2
  - anaconda:ipython
  - anaconda:jupyter>=1.0.0
  - anaconda:jupyterlab>=1.0.0
  - anaconda:pandas
  - anaconda:pytest==4.4.0
  - anaconda:dask==1.2.2
  - anaconda:datashader
  - anaconda:line_profiler
  - conda-forge:geopandas==0.5.1
  - conda-forge:descartes
  - conda-forge:pydotplus 
  - conda-forge:tqdm  
  - conda-forge:hypothesis 
  - conda-forge:luigi
  - conda-forge:altair>=3.0.0
  - conda-forge:missingno
  - conda-forge:fastapi==0.35.0
  - conda-forge:pydantic
  - conda-forge:locust
  - conda-forge:vdom
  - conda-forge:sqlalchemy
  - conda-forge:boto3
  - conda-forge:chalice==1.9.1
  - conda-forge:uvicorn
  - conda-forge:numba==0.44.1
  - conda-forge:cookiecutter
  - conda-forge:poetry==0.12.16
  - conda-forge:sphinx
  - conda-forge:graphviz
  - conda-forge:python-graphviz
  - conda-forge:pre-commit
  - dvc
  - pip
    